### ISSUE TITLE
目前的item弹出位置

### ISSUE THREAD

**Issue by huyue05** [CarGuo/CustomActionWebView#1]
目前的item位置 是基于原来系统的弹出位置来做的。
在部分手机上，这些选择框会位于右上角。
能不能直接弹在选择框的上面，

**Comment by CarGuo** [comment]
是的，因为目前的弹出是系统，低版本是在右上角，后面可以考虑纯粹用自定义么弹出。目前简单实现吧

**Comment by huyue05** [comment]
能说一下自定义如果要做的话，思路从哪入手么。主要还是获取位置，一个是按下那个点 另一个是后面的那个点，群主有什么思路吗？

**Comment by CarGuo** [comment]
主要重点还是在获取弹出位置，目前的思路是和获取选择文本一样，用js，其实很久前已经有这么做的，只是效果还不是很好。
