### ISSUE TITLE
自定义的菜单中有系统默认的选项

### ISSUE THREAD

**Issue by codeccc** [CarGuo/CustomActionWebView#3]
在我小米Note3上,通过demo实现的效果长按第一次会弹出所期望的菜单效果,但是拖动那个选择球以后菜单上会把原本移除的菜单选项也添加上去

**Comment by CarGuo** [comment]
不是很理解场景

**Comment by codeccc** [comment]
![1](https://user-images.githubusercontent.com/22289073/37499474-d8dd4b10-28fe-11e8-9030-428eabb78ae3.png)
![2](https://user-images.githubusercontent.com/22289073/37499475-d9244f24-28fe-11e8-8ee8-a3a654200a81.png)
![3](https://user-images.githubusercontent.com/22289073/37499476-d96ce130-28fe-11e8-81cf-ed9085551e48.png)

**Comment by CarGuo** [comment]
最后一张图的出现条件是？

**Comment by codeccc** [comment]
拖动红色的圆圈选择更多文字,然后点击选项右边的三个点弹出来的

**Comment by CarGuo** [comment]
哦，是有点右边三个点啊，因为这个应该是系统动态加上的，估计不受控制

**Comment by codeccc** [comment]
好吧,我昨天也是翻了很久源码也找不到突破点,感觉是没办法了
