### ISSUE TITLE
复制之后如何粘贴呢

### ISSUE THREAD

**Issue by Pom115** [CarGuo/CustomActionWebView#4]
如题，其实复制和粘贴都好办，但是在webview里复制文本之后如何粘贴到webview加载的H5界面的输入框中；另外有个延伸问题，WebView中加载的H5界面调用系统键盘，系统键盘输入的时候是怎么把数据写到H5界面输入框中的，另外如果使用的是系统复制粘贴功能，粘贴的时候数据是怎么写到H5界面输入框中的，原生系统是怎么通过webview获取到H5界面输入框控件的。如果大神知道的话还请指点一二为谢

**Comment by CarGuo** [comment]
问题1：复制后自动黏贴到h5的输入框？？这个可以复制后调用h5注册号的js接口通知它

**Comment by CarGuo** [comment]
问题2，系统键盘把输入输入h5的过程你应该不需要处理吧。回到问题1中，已经把内容复制到系统粘贴板，你完全可以自己的手动到输入框长按黏贴过去。

这一些都是系统的浏览器内核处理，至于怎么获取，这个就是浏览器内部逻辑了···

**Comment by Pom115** [comment]
复制后，长按弹出的菜单还是代码中写的这个菜单，不是系统中的复制粘贴菜单所以没法手动粘贴

**Comment by Pom115** [comment]
其实我现在遇到的问题就是按你的写法可以自定义复制菜单，并且把H5的内容复制到系统剪切板中，但是没法粘贴啊

**Comment by CarGuo** [comment]
粘贴的话，应该是长按弹出来的黏贴选项被屏蔽了，你过滤的时候，不要过滤掉粘贴选择试试，判断下
